version: '2'

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: migrate_example
      POSTGRES_DB: migrate_example
      POSTGRES_PASSWORD: development
    ports:
      - 5432:5432
    volumes:
      - '.data/postgresql:/var/lib/postgresql/data'
